2020-10-19 17:54:15,219 INFO    MainThread:5584 [wandb_init.py:_log_setup():292] Logging user logs to wandb\run-20201019_175415-1yz4tus8\logs\debug.log
2020-10-19 17:54:15,220 INFO    MainThread:5584 [wandb_init.py:_log_setup():293] Logging internal logs to wandb\run-20201019_175415-1yz4tus8\logs\debug-internal.log
2020-10-19 17:54:15,220 INFO    MainThread:5584 [wandb_setup.py:_flush():69] setting env: {}
2020-10-19 17:54:15,220 INFO    MainThread:5584 [wandb_setup.py:_flush():69] setting user settings: {'email': 'delimited@live.com'}
2020-10-19 17:54:15,221 INFO    MainThread:5584 [wandb_setup.py:_flush():69] multiprocessing start_methods=spawn
2020-10-19 17:54:18,431 INFO    MainThread:5584 [wandb_run.py:_console_start():1276] atexit reg
2020-10-19 17:54:18,441 INFO    MainThread:5584 [wandb_run.py:_redirect():1146] redirect: SettingsConsole.WRAP
2020-10-19 17:54:18,442 INFO    MainThread:5584 [wandb_run.py:_redirect():1177] Wrapping output streams.
2020-10-19 17:54:18,442 INFO    MainThread:5584 [wandb_run.py:_redirect():1193] Redirects installed.
2020-10-19 17:54:18,547 INFO    MainThread:5584 [wandb_run.py:_atexit_cleanup():1249] got exitcode: 1
2020-10-19 17:54:18,548 INFO    MainThread:5584 [wandb_run.py:_restore():1221] restore
2020-10-19 17:54:18,841 INFO    MainThread:5584 [wandb_run.py:_wait_for_finish():1360] got exit ret: uuid: "a6fccb62298245189048807f54966989"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      total_bytes: 816
    }
  }
}

2020-10-19 17:54:20,871 INFO    MainThread:5584 [wandb_run.py:_wait_for_finish():1360] got exit ret: uuid: "e4bc020111ab407682163fc5bb00fea4"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 2762
      total_bytes: 2762
    }
  }
}

2020-10-19 17:54:22,132 INFO    MainThread:5584 [wandb_run.py:_show_files():1554] logging synced files
2020-10-19 17:54:22,231 INFO    MainThread:5584 [internal.py:handle_exit():137] Internal process exited
